
var nome = prompt ("Olá! Seja muito bem vindo a nossa história, antes de começar, qual seu nome?");
 alert (nome + "," + " essa história possuí 9 finais, alguns mais curtos e outros mais desenvolvidos, dica: tente jogar todos para viver a experiência em diferentes dimensões (você entenderá). E lembre-se: nunca confie num mundo que você não conhece");

var conteudoA = "<img src='imagens/personagem.gif'/> <h2 span class = 'titulo'> O inicio da jornada </span></h2></div><p span class = 'texto'>Eu sei.. Eu sei, muitas vezes quando se tem 10 anos qualquer coisa se parece com o fim do mundo, até quando seus pais não te deixam brincar com uma espada de verdade, por que segundo você, um cavaleiro precisa estar preparado para qualquer coisa. Mas agora você andou demais e se perdeu.. Se na sua mochila não houver coisas que te ajudem o suficiente até você fazer 18 anos e conseguir arrumar um emprego, então é hora de começar a pensar em como voltar para casa.</span></p> <b><p span class = 'pergunta'> Vamos lá, para qual lado devemos ir?</p><b> <button onclick='carregarConteudo(conteudo2)'>Ir para a Esquerda</button> <button onclick='carregarConteudo(conteudo3)'>Ir para a Direita</button>";

var conteudo2 = "<img src='imagens/golem.gif'/> <p span class = 'texto'>O caminho, por algum motivo, estava bloqueado por uma pedra grande e.. barulhenta? Você tentou empurra-la mas foi inutil comparando o tamanho da pedra com a sua força. De repente, aos poucos e grunhindo, um Golem de pedra surge em sua frente. Talvez não tenha sido uma boa ideia.</span></p> <p span class = 'pergunta'>O Golem, que antes estava adormecido, agora te olha, com certa apatia. Agora, qual seria a melhor e mais segura opção?</p> <button onclick='carregarConteudo(conteudo5)'>Distrair o Golem e correr</button> <button onclick='carregarConteudo(conteudo4)'>Ficar e tentar argumentar</button>";

var conteudo3 = "<img src='imagens/golem.gif'/>> <p span class = 'texto'>O caminho, por algum motivo, estava bloqueado por uma pedra grande e.. barulhenta? Você tentou empurra-la mas foi inutil comparando o tamanho da pedra com a sua força. De repente, aos poucos e grunhindo, um Golem de pedra surge em sua frente. Talvez não tenha sido uma boa ideia..</p> <p span class = 'pergunta'> O Golem, que antes estava adormecido, agora te olha, com certa apatia. Agora, qual seria a melhor e mais segura opção?</p> <button onclick='carregarConteudo(conteudo5)'>Distrair o Golem e correr</button> <button onclick='carregarConteudo(conteudo4)'>Ficar e tentar argumentar</button>";

var conteudo4 = "<img src='imagens/placas.gif'/><p span class = 'texto'>" + nome + "," + " disfarçando seu medo, decide ficar para argumentar, e explica ao golem que se perdeu de sua casa e que precisa voltar, o golem por sua vez, não fala, apenas escreve alguns rabiscos pouco legíveis (onde também pode se perceber que ele é um ótimo artista). É dito nos rabiscos que, se ele quiser voltar ao seu mundo, precisa retornar em frente a passagem de onde ele veio e recitar um antigo poema, contido dentro do livro das criaturas. Livro esse, que o golem diz ter visto certa vez na biblioteca do cachorro quente louco.</p> <p>O golem, decide partir junto com você, pois, como já havia sido acordado, só iria conseguir dormir na próxima manhã. Vocês dois seguem juntos por um caminho estreito dentro da floresta, onde logo a frente é possível avistar uma vila de casas, todas feitas de cogumelos. O golem explica, que aquelas são as casas dos moradores do distrito de cogumelândia, a vila de pessoas mais chatas do mundo. </p> <button onclick='carregarConteudo(conteudo6)'>Seguir por congumelândia</button> <button onclick='carregarConteudo(conteudo7)'>Ir por outro caminho</button>";

var conteudo5 = "<img src='imagens/placas.gif'/><p span class = 'texto'>Você rapidamente joga sua mochila no chão e a abre, com movimentos rápidos dignos de um ninja você pega um par de meia e joga no Golem para tentar distraí-lo, haha, por essa ele não esperava! Porém, nada acontece, o Golem sequer se mexeu, apenas o olha com certa apatia. Percebendo que o Golem não o fez mal algum, você resolve contar a sua situação, e explica que se perdeu de sua casa e que precisa voltar, o golem por sua vez, não fala, apenas escreve alguns rabiscos pouco legíveis (onde também pode se perceber que ele é um ótimo artista). É dito nos rabiscos que, se ele quiser voltar ao seu mundo, precisa retornar em frente a passagem de onde ele veio e recitar um antigo poema, contido dentro do livro das criaturas. Livro esse, que o golem diz ter visto certa vez na biblioteca do cachorro quente louco. </p><p>O golem, decide partir junto com você, pois, como já havia sido acordado, só iria conseguir dormir na próxima manhã. Vocês dois seguem juntos por um caminho estreito dentro da floresta, onde logo a frente é possível avistar uma vila de casas, todas feitas de cogumelos. O golem explica, que aquelas são as casas dos moradores do distrito de cogumelândia, a vila de pessoas mais chatas do mundo. </p> <button onclick='carregarConteudo(conteudo6)'>Seguir por congumelândia</button> <button onclick='carregarConteudo(conteudo7)'>Ir por outro caminho</button>";

var conteudo6 = "<img src='imagens/ganso.gif'/><p span class = 'pergunta'> Vocês dois decidem ir por cogumelândia, fazer o que né? Porém logo na entrada da cidade, há um ganso que os informam que para continuar, será necessário pagar a passagem de 2 botões de calça.</p> <button onclick='carregarConteudo(conteudo8)'>Reclamar que esta muito caro</button> <button onclick='carregarConteudo(conteudo9)'>Dar dois botões de sua calça</button>";

var conteudo7 = "<img src='imagens/placas.gif'/><p span class = 'texto'> Vocês decidem ir por outro caminho " + "," + nome +"," + " se vira para o golem e diz que nunca gostou de pessoas chatas, e, que se havia uma cidade de pessoas chatas, então era melhor procurar a cidade de pessoas legais. Os dois seguem pelo outro lado e se deparam com uma bifurcação, onde as placas na entrada dizem “cidade das pessoas legais” e a outra “cidade das pessoas muito, muito legais mesmo hehe”. Você diz ao golem que é melhor eles irem pela cidade das pessoas legais, por que pessoas MUITO MUITO legais acabam se tornando chatas, Golem escreve que gostaria de ter encontrado pessoas legais na vida dele, mas que sempre foi esquecido. Os dois adentram a cidade das pessoas legais, e avistam muitas casas enfeitadas e bonitas, comércios e várias crianças não-humanas brincando na pracinha.</p> <button onclick='carregarConteudo(conteudo10)'>Perguntar a alguém sobre a biblioteca e o livro </button> <button onclick='carregarConteudo(conteudo11)'>Brincar com as crianças</button>";

var conteudo8 = "<img src='imagens/ganso.gif'/><p span class = 'texto'> - Ei você esta louco! Eu não vou te dar dois botões de minha calça e ir andando de shortinho o resto do caminho! está muito caro essa entrada, só estamos de passagem, iremos até a biblioteca fazer nossos estudos e voltaremos, sequer passaremos essa noite aqui! <br>O ganso os alerta: -Todos que chegam dizem isso, muito cuidado, por que depois que chegam, é difícil voltarem juntos. Me paguem algum outro objeto e os deixarei passar. Golem lhe dá um origami de ganso que ele havia feito outra vez, isso foi o suficiente.</p> <button onclick='carregarConteudo(conteudo12)'>Perguntar a alguém onde fica a biblioteca</button> <button onclick='carregarConteudo(conteudo13)'>Encontrar por conta própria</button>";

var conteudo9 = "<img src='imagens/cuequinha.gif'/><p span class = 'texto'> Caramba! Mas parece que não há muito o que fazer, você deus os dois botões de sua calça, porém teve de continuar cidade a dentro sem calças (embaraçoso...). Andando pela vila, vocês dois conseguem avistar bastante comércios e pessoas. </p> <button onclick='carregarConteudo(conteudo12)'>Perguntar a alguém onde fica a biblioteca</button> <button onclick='carregarConteudo(conteudo13)'>Encontrar por conta própria</button>";

var conteudo10 = "<img src='imagens/esquilinha.gif'/> <p span class = 'texto'> Os dois decidem entrar na pousada da sonequinha (uma esquilinha). Chegam na recepção e a perguntam sobre uma biblioteca que guarde livros antigos. Logo de cara a esquilinha os trata muito bem, mas ela é rápida e não para! Em um segundo os serviu café, biscoitos, uma poltrona macia e cobertores quentinhos, caramba, mas que pessoa legal!</p> <button onclick='carregarConteudo(conteudo14)'>Perguntar sobre a biblioteca!!</button> <button onclick='carregarConteudo(conteudo15)'>Ah, que soninho..</button>";

var conteudo11 = "<img src='imagens/personagem.gif'/><p span class = 'texto'> " + nome +" corre até as crianças e pergunta se pode brincar com elas, as crianças logo se animam e o explicam as suas brincadeiras. Agora brincaremos de esconde-esconde! Você conhece essa? Eles correm por entre a cidade gritando para se esconder, O golem, por outro lado, observa de longe, nunca foi bom em se comunicar com outras pessoas, pois tem medo de se enturmar... De tanto correr e brincar, você percebe que perdeu seu amigo golem de vista, puxa vida..</p> <button onclick='carregarConteudo(conteudo16)'>Voltar para encontrar ele</button> <button onclick='carregarConteudo(conteudo17)'>Continuar a brincar</button>";

var conteudo12 = "<img src='imagens/florzinha.gif'/> <p span class = 'texto'> Os dois veem de longe uma senhora florzinha fazendo suas unhas na calçada de sua casa, eles se aproximam e perguntam para ela onde fica a biblioteca, a mesma, apenas olha para eles de cima a baixo e continua o que estava fazendo. Os dois se entreolham, dão de ombro e continuam a andar, parece que Golem tinha razão, Cogumelândia não tem os habitantes maaaaais legais do mundo.</p>  <button onclick='carregarConteudo(conteudo18)'>Ir para direita</button> <button onclick='carregarConteudo(conteudo19)'>Ir para a esquerda</button>";

var conteudo13 = "<img src='imagens/personagem.gif'/><img src='imagens/golem.gif'/><p span class = 'texto'> Os dois andam por muitos minutos, e mesmo dando pinta de turistas realmente perdidos, ninguém da vila tenta ajuda-los.</p> <button onclick='carregarConteudo(conteudo18)'>Ir para direita</button> <button onclick='carregarConteudo(conteudo19)'>Ir para a esquerda</button>";

var conteudo14 = "<img src='imagens/esquilinha.gif'/> <p span class = 'texto'> Você é firme no seu propósito e não se deixa abater pelo cansaço e questiona a moça sobre a biblioteca, a esquilinha, porém, fala que naquela cidade não existe uma biblioteca, apenas um gafanhoto que recita poesias na praça da rua vez ou outra. Você explica que precisa ir na biblioteca pegar o livro que o ajudará a retornar para sua casa, pois ali não é seu mundo, no entanto, a esquilinha responde que o melhor para ele é continuar lá, por que todas as pessoas que adentraram aquele mundo, nunca conseguiram sair. (tandandan) </p> <button onclick ='carregarConteudo(conteudo22)'>Chamar Golem para ir embora</button> <button onclick='carregarConteudo(conteudo23)'>Aceitar seu destino</button>";

var conteudo15 = "<img src='imagens/mimir.gif'/><p span class = 'texto'> Você e o golem decidem dormir... Que mal tem? Pobre garoto, está tão cansado de sua jornada, é como se... Em outra dimensão, você estivesse fazendo isso várias e várias vezes, como se alguém controlasse suas escolhas. Se vocês tivessem conseguido achar o livro, saberiam... Você não pode consumir nada no mundo das criaturas, sequer pode dormir, deve completar toda sua jornada sem pestanejar, como um cavaleiro faria. Agora está tudo acabado, sua jornada termina aqui,"+ nome +",você sucumbiu ao sono eterno...</p> <p><b>A sua jornada não termina aqui! Tente outros caminhos e você conseguirá finaliza-la, boa sorte cavaleiro(a)!</b></p><br><button onclick = 'carregarConteudo(conteudoA)'>Recomeçar a história</button>"; /*1 Final*/

var conteudo16 = "<img src='imagens/coelhinho.gif'/><img src='imagens/briga.gif'/><p span class = 'texto'>Você se separa do grupo das crianças para procurar Golem, ele é um gigante de pedra então não deve ser muito dificl distinguir ele do resto da cidade, eu não havia percebido antes, mas aqui é realmente muito bonito, acho que a euforia fez tudo passar muito despercebido. Você observa os comércios abrindo e dá bom dia para as pessoas, o ar fresco da vila o deixa alegre, você se sente feliz e completo... Depois de andar por um tempo, um coelhinho de suéter o para de repente. - E-ei senhor, eu não lhe conheço, desculpa te parar assim, mas logo ali na frente, eu acho que vi umas duas pessoas idênticas a você! Eu juro, juro! Eles carregavam um livro estranho, mas... Cadê o seu?  Você logo percebe que o livro que ele citou, deve ser aquele que a esquilinha disse que sequer existia pois não havia uma biblioteca aqui na cidade, mas, pessoas idênticas a você, como isso é possível? Você rapidamente corre até a fonte o mais rápido que consegue, e, chegando lá consegue ver com seus próprios olhos, tudo o que o coelhinho falou era verdade! </p> <br> <p> No rio, há uma placa (rio do gatinho-não-humano), mas que rio é esse? Eu nunca tinha visto ele antes! Correndo ladeira a cima você chega e vê uma cena que lhe choca? O que é isso? Um cachorro quente falante, um golem igual ao seu amigo e... duas versões idênticas a você? Eles parecem estar numa briga, e perto deles, o livro caído no chão junto com páginas de diário, será que... Será que é isso que te levaria para casa? Você rapidamente salta entre eles para separar a briga. Você grita:  Parem, parem agora! Vocês não são selvagens! Talvez essa pessoa pelada com uma mordida de cobra no seu braço até seja, mas vejam, somos idênticos e aparentemente, buscamos a mesma coisa, ir para casa! Precisamos fazer isso antes que as coisas fujam mais ainda de controle, peguem essas páginas, vamos correr para a entrada da floresta e recitar esse poema já! Essas realidades paralelas tem de parar, estão controlando nossas escolhas, mas precisamos nos unir para acabar com isso! Ouviu bem pessoa má que está controlando a vida de crianças! </p> <button onclick ='carregarConteudo(conteudo40)'> Destino final</button>"; /*conectar final*/

var conteudo17 = "<img src='imagens/coelhinho.gif'/><img src='imagens/briga.gif'/><p span class = 'texto'> Você decide continuar brincando com as crianças, afinal, golem não se perderia aqui nessa Vila, provavelmente estava apenas observando de longe. Você continua correndo com as crianças e fazendo mais amizades, depois de brincar por um tempo, um coelhinho de suéter o para de repente. - E-ei senhor, eu não lhe conheço, desculpa te parar assim, mas logo ali na frente, eu acho que vi umas duas pessoas idênticos a você! Eu juro, juro! Eles carregavam um livro estranho, mas... Cadê o seu?  Você logo percebe que o livro que ele citou, deve ser aquele que a esquilinha disse que sequer existia pois não havia uma biblioteca aqui na cidade, mas, pessoas idênticas a você, como isso é possível? Você rapidamente corre até a fonte o mais rápido que consegue, e, chegando lá consegue ver com seus próprios olhos, tudo o que o coelhinho falou era verdade! </p> <br> <p> No rio, há uma placa (rio do gatinho-não-humano), mas que rio é esse? Eu nunca tinha visto ele antes! Correndo ladeira a cima você chega e vê uma cena que lhe choca? O que é isso? Um cachorro quente falante, um golem igual ao seu amigo e... duas versões idênticas a você? Eles parecem estar numa briga, e perto deles, o livro caído no chão junto com páginas de diário, será que... Será que é isso que te levaria para casa? Você rapidamente salta entre eles para separar a briga. Você grita:  Parem, parem agora! Vocês não são selvagens! Talvez essa pessoa pelado com uma mordida de cobra no seu braço até seja, mas vejam, somos idênticos e aparentemente, buscamos a mesma coisa, ir para casa! Precisamos fazer isso antes que as coisas fujam mais ainda de controle, peguem essas páginas, vamos correr para a entrada da floresta e recitar esse poema já! Essas realidades paralelas tem de parar, estão controlando nossas escolhas, mas precisamos nos unir para acabar com isso! Ouviu bem pessoa má que está controlando a vida de crianças! </p> <button onclick ='carregarConteudo(conteudo40)'> Destino final</button>"; /*conectar final*/

var conteudo18 = "<img src='imagens/cachorro.gif'/> <p span class = 'texto'> Vocês decidem ir pela direita, e chegam justamente na esquina da biblioteca, onde avistam o Cachorro quente louco, muito louco por que a sua fechadura quebrou e assim ele não consegue abrir o estabelecimento. Vocês dois correm para perto e checam a situação, o dono da biblioteca é o cachorro quente louco, um hot dog que surta por qualquer coisa, mas aparentemente você não vai conseguir o livro se não entrar na biblioteca.</p> <button onclick='carregarConteudo(conteudo20)'>Oferecer ajuda para trocar as peças da fechadura</button> <button onclick='carregarConteudo(conteudo21)'>Esperar ele conseguir abrir a porta</button>";

var conteudo19 = "<img src='imagens/cachorro.gif'/> <p span class = 'texto'> Vocês dois decidem ir pela esquerda, porém mais a frente percebeme que é uma rua sem saída, cuja placa no final dela diz 'Ainda estamos construindo a Cogumelândia 2.0, volte mais tarde!'. - Droga - vocês dois pensam, e retornam a entrada da rua, onde o único caminho que lhes restam é pela direita, no entanto acertaram em cheio! Chegaram justamente na esquina da biblioteca, onde avistam o Cachorro quente louco, muito louco por que a sua fechadura quebrou e assim ele não consegue abrir o estabelecimento. Vocês dois correm para perto e checam a situação, o dono da biblioteca é o cachorro quente louco, um hot dog que surta por qualquer coisa, mas aparentemente você não vai conseguir o livro se não entrar na biblioteca.</p> <button onclick='carregarConteudo(conteudo20)'>Oferecer ajuda para trocar as peças da fechadura</button> <button onclick='carregarConteudo(conteudo21)'>Esperar ele conseguir abrir a porta</button> </p>";

var conteudo20 = "<img src='imagens/cachorro.gif'/> <p span class = 'texto'> Você e Golem se aproximam do cachorro quente e explicam toda a situação, e do por que precisam do livro, o cachorro quente sequer se importa, porque ele é biruta!!! </p> <button onclick ='carregarConteudo(conteudo24)'>Quebrar a porta com seu pé de cabra portatíl</button> <button onclick ='carregarConteudo(conteudo25)'>Subornar a porta com uma barra de cereal mordida</button>";

var conteudo21 = "<img src='imagens/cachorro.gif'/> <p span class = 'texto'> Você e Golem chegam do lado dele e ficam esperando ele conseguir abrir a porta. Cachorro quente olha para vocês e grita: - Tão esperando o que?? Por acaso vocês são mais birutas do que eu?? Me ajudem logo seus lelés da cuca! </p> <button onclick ='carregarConteudo(conteudo24)'>Quebrar a porta com seu pé de cabra portatíl</button> <button onclick ='carregarConteudo(conteudo25)'>Subornar a porta com uma barra de cereal mordida</button>";

var conteudo22 = "<img src='imagens/golem.gif'/><p span class = 'texto'>Você corre em direção a Golem para chama-lo, mas sequer havia percebido, já era manhã, e ele havia entrado no modo hibernação dos golens, só acordaria daqui há muitas horas, não importava o quanto você o chamava, ele sequer se movia do lugar. </p> <button onclick='carregarConteudo(conteudo26)'>sair e ir explorar a cidade</buttom> <button onclick='carregarConteudo(conteudo27)'>Continuar na pousada com Golem</button>";

var conteudo23 = "<img src='imagens/personagem.gif'/><p span class = 'texto'>Você pensa consigo mesmo, que nos poucos momentos que havia passado naquela cidade, tinha se sentido muito bem, como se lá, pudesse ser o cavaleiro que sempre sonhou, afinal, era um mundo de criaturas mágicas, e que criança não gostaria de viver isso? </p> <button onclick='carregarConteudo(conteudo26)'>Ir explorar a cidade</buttom> <button onclick='carregarConteudo(conteudo27)'>Continuar na pousada com Golem</button>";

var conteudo24 = "<img src='imagens/livro.gif'/><p span class = 'texto'> Você decide utilizar seu pé de cabra para forçar a porta, utilizando todo seu conhecimento adquirido assistindo canais de TV de como sobreviver num ataque zumbi (ufa, valeu a pena), a cede e finalmente vocês chegam à biblioteca, " + nome + " e golem procuram entre as estantes do local, onde chegam na seção de livros esquecidos. Golem escreve que você deve procurar no capítulo das criaturas horrendas, página 72. Rapidamente o livro é aberto na página indicada. Porém... Metade da página havia sido arrancada. </p> <button onclick='carregarConteudo(conteudo28)'>Surtar e correr pelado</button> <button onclick='carregarConteudo(conteudo29)'>Pedir informação ao cachorro louco</button>";

var conteudo25 = "<img src='imagens/livro.gif'/><p span class = 'texto'> Você decide subornar a porta com sua barra de cereal mordida, afinal nem tudo é sobre violência, a porta o agradece, pois estava com muita fome, e em troca lhe dá uma dica:-Não confie muito nas portas e nos portais daquela cidade, e em seguida lhe dá um jab de direita. Caramba, isso doeu! <br> Você segue para dentro da biblioteca atordoado e com um olho roxo, vocês procuram entre as estantes do local, onde chegam na seção de livros esquecidos. O golem escreve que o você deve procurar no capítulo das criaturas horrendas, página 72. Rapidamente o livro é aberto na página indicada. Porém... Metade da página havia sido arrancada. </p> <button onclick='carregarConteudo(conteudo28)'>Surtar e correr pelado</button> <button onclick='carregarConteudo(conteudo29)'>Pedir informação ao cachorro louco</button>";

var conteudo26 = "<img src='imagens/esquilinha.gif'/><p span class = 'texto'>Depois de horas e horas de espera, e horas da Sra. Esquilinha contando sobre a vida dela e vida de todos os seus hospedes chatos, Golem finalemente acorda de sua hibernação. Você da uma pulo do sofá e corre na direção dele: - Cara! Você finalmente acordou! Vamos logo, vamos olhar o resto da cidade, para de ficar aí dormindo igual pedra. Vocês dois saem para passear, o pessoal parece sempre muito gentil, chega a ser estranho. Há quase no final da cidade, uma fonte, com uma placa escrita (fonte mágica muito melhor que a da cidade ao lado). Eles parecem competir em tudo não é mesmo? Você pode jogar um fio de seu cabelo na fonte e pedir o que quiser, você pensa incessantemente entre voltar para casa ou continuar aqui, você não sabe se fez uma boa escolha, sente saudade dos seus pais e das suas aventuras lá em cima... É tudo tão confuso </p> <button onclick= 'carregarConteudo(conteudo30)'>Voltar para casa</button> <button onclick='carregarConteudo(conteudo31)'>Continuar nesse mundo</button>";

var conteudo27 = "<img src='imagens/mimir.gif'/><p span class = 'texto'> As horas parecem se arrastar, seu amigo não acorda e sua única distração é o tic tac do relógio na parede, além da Sra. Esquilinha fazendo tricô do seu lado enquanto assiste um programa de domingo a tarde qualquer, sem perceber, você adormece. <br> Golem acorda, muitas horas depois da sua hibernação, e o vê adormecido no sofá, num sono profundo e cansado, como se anos houvesse se passado, ele tenta o acordar, porém nada dá certo, Golem percebe seu destino, percebe que perdeu o único amigo que um já teve, ele escreve em seu caderninho um poema junto com um desenho de despedida e deixa ao seu lado, Golem parte sozinho de volta para a floresta onde ele vivia, foram bons momentos juntos... </p> <p><b>A sua jornada não termina aqui! Tente outros caminhos e você conseguirá finaliza-la, boa sorte cavaleiro(a)!</b></p><br><button onclick = 'carregarConteudo(conteudoA)'>Recomeçar a história</button>"; /*2 Final*/

var conteudo28 = "<img src='imagens/cuequinha.gif'/><p span class = 'texto'> Caso escolha correr pelado, o garoto avança sem direção pelas ruas enquanto escandaliza toda a população local. Quando finalmente decide descansar próximo a uma fonte, ouve duas senhoras (com vozes muito chatas) comentarem:<br> -Estes humanos são todos mal-educados, não podem ver uma oportunidade de correr pelado pelas ruas que não pensam duas vezes. <br> -Sim, lembra daquele que se perdeu por aqui e tomou um banho na fonte da praça? <br> -Claro que lembro, dizem que ele causou uma confusão na biblioteca do cachorro quente doido e tá escondido perto do rio do gatinho-não-filhote. <br>-Bem que ele podia ter destruído aquela loja, aquele cachorro quente é muito doido. <br>-Sim, muito doido. <br>-Maluco. <br>-Biruta.</p> <p> Que velhas chatas! Você sente vontade de assusta-las fingindo ser um maluco biruta, mas também precisa ir falar para seus amigos a informação que havia conseguido</p> <button onclick='carregarConteudo(conteudo32)'>assustar elas e depois ir contar</button> <button onclick='carregarConteudo(conteudo33)'>Ir contar a eles</button>";

var conteudo29 = "<img src='imagens/cachorro.gif'/><p span class = 'texto'>" + nome + " vai até cachorro louco e fala sobre a página faltando, o mesmo responde que não checou o estado do livro depois que ele foi entregue pela última vez, mas que a última pessoa quem o pegou, também era um humano que parecia perdido, provavelmente voltando para o início da floresta. Você pergunta a quanto tempo isso aconteceu, e cachorro quente responde que na verdade essa pessoa que pegou o livro, também foi o desgraçado que quebrou a porta dele!! Você pergunta ao cachorro quente se ele sabe o paradeiro dele, e ele o reponde, que, a última vez que o viu, ele só havia pego o livro e ido em direção à praça da cidade, onde fica a fonte mágica dos desejos. </p> <button onclick='carregarConteudo(conteudo34)'>Ir até a fonte</button> <button onclick='carregarConteudo(conteudo35)'>Perder as esperanças</button>";

var conteudo30 = "<img src='imagens/personagem.gif'/><p span class = 'texto'> Você tira um fio de seu cabelo e o observa em sua mão, olha para o lado e vê Golem com um olhar triste, não é como se você pudesse ver isso, afinal ele é de pedra, mas se os sentimentos dele fossem visivéis, com certeza tristeza o definiria. Você diz a ele que sente muito, ele é um ótimo amigo, mas que precisa voltar para casa, sente saudades de casa. Golem desenha em seu caderninho vocês dois juntos, isso é uma despedida...</p> <p><br>Você joga o fio de cabelo na fonte e fecha bem os olhos, pede com todas as forças para voltar para casa, Golem apenas observa a sua partida, foram bons momentos, espero que esteja feliz com sua escolha. </p> <br><p><b>Ei, amigo(a), existem outros finais, continue tentando, boa sorte!</p> <b>br><button onclick = 'carregarConteudo(conteudoA)'>Recomeçar a história</button><"; /*3final*/

var conteudo31 = "<img src='imagens/mimir.gif'/><p span class = 'texto'> Você se afasta rapidamente da fonte e pensa consigo mesmo: Eu estou feliz aqui, sinto que fiz a escolha certa, tenho meu novo amigo Golem, posso brincar de ser o que eu quiser aqui, além de ter encontrado uma cidade incrível. Sim, eu estou certo de minha escolha, quero ficar aqui, e sei que caso eu me arrependa, posso voltar nessa fonte e pedir para voltar para casa. Você corre feliz junto de golem e continuam a explorar a cidade juntos. Eu gostaria que esse fosse mais um final feliz, mas você sabe, nem tudo é perfeito nesse mundo de criatura fantásticas, um humano não conseguiria viver nesse mundo, pois até adormecer aqui é um perigo, de todo jeito, espero que ele tenha aproveitado seus últimos momentos num mundo mágico, e conhecido bons amigos, nem tudo sai como esperávamos, não é? </p><br><button onclick = 'carregarConteudo(conteudoA)'>Recomeçar a história</button>"; /*4final*/

var conteudo32 = "<img src='imagens/gatinho.gif'/> <p span class = 'texto'> Você sai de trás de onde havia se escondido rosnando feito um biruta, as duas senhoras se assustam e uma delas lhe bate com um guarda-chuva na cabeça (péssima ideia), você corre de volta ao encontro de seus amigos e conta a eles tudo o que ouviu, eles concordam e vocês três correm até o rio, e chegando lá, avistam o gatinho que vigia o rio, ele é fofinho e de olho grande, como um carinha pequeno desses consegue proteger o rio de possíveis invasores? Chegando perto para pedir informações, o gatinho se torna um super gato, puxa sua katana e os questiona: O QUE QUEREM NO MEU RIO? (Ah, agora eu entendi como ele consegue proteger...)</p> <p>Perguntar sobre o humano pelado que correu para lá ou o cachorro quente subir em cima do golem e depois você subir em cima do cachorro quente para se mostrarem mais ameaçadores?</p> <button onclick='carregarConteudo(conteudo36)'>Perguntar sobre o humano</button> <button onclick='carregarConteudo(conteudo37)'>Se tornarem ameaçadores</button>";

var conteudo33 = "<img src='imagens/gatinho.gif'/><p span class = 'texto'>Você corre de volta ao encontro de seus amigos e conta a eles tudo o que ouviu, eles concordam e vocês três correm até o rio,e chegando lá, avistam o gatinho que vigia o rio, ele é fofinho e de olho grande, como um carinha pequeno desses consegue proteger o rio de possíveis invasores? Chegando perto para pedir informações, o gatinho se torna um super gato, puxa sua katana e os questiona: O QUE QUEREM NO MEU RIO? (Ah, agora eu entendi como ele consegue proteger...) </p> <p> Perguntar sobre o humano pelado que correu para lá ou o cachorro quente subir em cima do golem e depois você subir em cima do cachorro quente para se mostrarem mais ameaçadores?</p>  <button onclick='carregarConteudo(conteudo36)'>Perguntar sobre o humano</button> <button onclick='carregarConteudo(conteudo37)'>Se tornarem ameaçadores</button>";

var conteudo34 = "<img src='imagens/briga.gif'/><p span class = 'texto'> Droga! Parece que só surgem empecilhos nessa história! Mas, tudo bem, não vamos perder a esperança, você precisa voltar para casa!</p> <p>Você, cachorro quente doido e Golem correm até lá, mas... Eu nunca vi isso antes, vocês conseguem chegar até a fonte, porém, há mais 3 versões suas lá, idênticos? Gêmeos? Todos vocês carregam o mesmo livro, é como se... Em várias outras realidades paralelas, vocês tivessem tomado o mesmo rumo, tivessem tido as mesmas escolhas... E agora se encontraram</p> <p> Porém, por algum motivo, esse lugar está uma bagunça! tem duas pessoas que parecem estar lutando, um assistindo e você que acabou de chegar, além do cachorro quente e um Golem. Rapidamente, a pessoa que assistia a briga entra no meio das duass que brigavam e começa a gritar: <br> - Parem, parem agora! Vocês não são selvagens! Talvez essa pessoa pelado com uma mordida de cobra no seu braço até seja, mas vejam, somos idênticos e aparentemente, buscamos a mesma coisa, ir para casa! Precisamos fazer isso antes que as coisas fujam mais ainda de controle, peguem essas páginas, vamos correr para a entrada da floresta e recitar esse poema já! Essas realidades paralelas tem de parar, estão controlando nossas escolhas, mas precisamos nos unir para acabar com isso! Ouviu bem pessoa má que está controlando a vida de crianças!</p> <button onclick ='carregarConteudo(conteudo40)'> Destino final</button>" /*conectar final*/

var conteudo35 = "<img src='imagens/mimir.gif'/><p span class = 'texto'> Ei, não é assim que fazemos aqui! Perder as esperanças não é uma opção, continue tentando, eu tenho certeza que você se dará bem e seu final feliz irá chegar! Mas mesmo assim, eu sinto muito... Não queria que você chegasse nesse estado, não queria te desapontar e fazer você pensar que não conseguiria, acho que é um adeus, né? Mas não desista, esse não é o seu único destino.</p> <br><button onclick = 'carregarConteudo(conteudoA)'>Recomeçar a história</button>" /*5 final*/

var conteudo36 = "<img src='imagens/mochila.gif'/> <p span class = 'texto'> Você questiona ao gatinho sobre o humano pelado que correu para lá, provavelmente com as páginas de algum livro, Gatinho guarda a katana e lhe responde que sim, tinha visto alguém desnorteado por essas bandas, que lembrava muito você, que ele havia subido ladeira a cima do rio, mas fazia pouco tempo, se correr, ainda consegue alcança-lo. Rapidamente, você, golem e cachorro quente correm na direção onde o gatinho apontou. A estrada se torna cada vez mais estreita e sinuosa, Golem te leva nas costas e cachorro quente doido está ainda mais doido para encontrar o safado que quebrou a sua porta! <br>Mais adiante, vocês conseguem avistar uma mochila jogada no chão, dentro dela, está a folha que faltava do livro, com o poema a ser recitado, porém junto com ela há uma folha de diário, escrita à mão com uma caligrafia parecida com a sua. Na folha é dito que, a pessoa quem havia escrito isso, após se perder perto do rio do gatinho-não-humano, havia sido mordido por uma cobra pessimista, cuja o veneno o fez perder a voz, impossibilitando-o de recitar o poema e ir embora para casa, o mesmo, furioso, correu para se esconder e guardar o poema junto a si, pois não queria que ninguém o tirasse dele, porque queria muito voltar para casa, mas... Sem voz, não sabia como... Após lerem isso, os três se olham, muito entristecidos com o que aconteceu com o pobrezinho, até cachorro quente doido, se sente envergonhado por sua fúria, porém, antes que pudessem tomar alguma atitude, o desconhecido pelado e sem voz, pula neles furioso tentando a todo custo pegar a folha que contém o poema. </p> <br> Tentar pará-lo e explicar que você também está tentando voltar para casa ou lutar também? </br> <button onclick='carregarConteudo(conteudo38)'>Explicar a ele</button> <button onclick='carregarConteudo(conteudo39)'>Brigar também</button>";

var conteudo37 = "<img src='imagens/mochila.gif'/> <p span class = 'texto'> Vocês rapidamente fazem uma pose de ninja, cachorro quente sobe nas costas de Golem e você sobe nas costas de cachorro quente, o gatinho rapidamente guarda sua katana e se encolhe: - Tudo bem! Tudo bem! Como sabiam que eu tinha medo de montinhos? Digam logo o que querem aqui! Você fala ao gatinho sobre o humano pelado que correu para lá, provavelmente com as páginas de algum livro, Gatinho lhe responde que sim, tinha visto um alguém desnorteado por essas bandas, que lembrava muito você, que ele havia subido ladeira a cima do rio, mas fazia pouco tempo, se correr, ainda consegue alcança-lo. Rapidamente, você, golem e cachorro quente correm na direção onde o gatinho apontou. A estrada se torna cada vez mais estreita e sinuosa, Golem te leva nas costas e cachorro quente doido está ainda mais doido para encontrar o safado que quebrou a sua porta! <br>Mais adiante, vocês conseguem avistar uma mochila jogada no chão, dentro dela, está a folha que faltava do livro, com o poema a ser recitado, porém junto com ela há uma folha de diário, escrita à mão com uma caligrafia parecida com a sua. Na folha é dito que, a pessoa quem havia escrito isso, após se perder perto do rio do gatinho-não-humano, havia sido mordido por uma cobra pessimista, cuja o veneno o fez perder a voz, impossibilitando-o de recitar o poema e ir embora para casa, o mesmo, furioso, correu para se esconder e guardar o poema junto a si, pois não queria que ninguém o tirasse dele, porque queria muito voltar para casa, mas... Sem voz, não sabia como... Após lerem isso, os três se olham, muito entristecidos com o que aconteceu com o pobrezinho, até cachorro quente doido, se sente envergonhado por sua fúria, porém, antes que pudessem tomar alguma atitude, o desconhecido pelado e sem voz, pula neles furioso tentando a todo custo pegar a folha que contém o poema. </p> <br>Tentar pará-lo e explicar que você também está tentando voltar para casa ou lutar também?</br> <button onclick='carregarConteudo(conteudo38)'>Explicar a ele</button> <button onclick='carregarConteudo(conteudo39)'>Brigar também</button>";

var conteudo38 = "<img src='imagens/briga.gif'/><p span class = 'texto'> Mesmo tentando parara-lo e tentando mostrar que vocês estão em busca da mesma coisa, apenas querem ir para casa, que ele sequer percebeu que vocês são idênticos, apenas controlados de maneiras diferentes, e que vieram de realidades diferentes, aquele doido é imparável, parece que aquele veneno de cobra fez mesmo mal a ele! Porém, antes que ele pudesse machuca-lo de maneira séria, uma outra versão de vocês pula no meio da briga para separa-los (outra versão? Caramba, parece até que essa história foi controlada de diversas formas!) <br> - Parem, parem agora! Vocês não são selvagens! Talvez essa pessoa pelada com uma mordida de cobra no seu braço até seja, mas vejam, somos idênticos e aparentemente, buscamos a mesma coisa, ir para casa! Precisamos fazer isso antes que as coisas fujam mais ainda de controle, peguem essas páginas, vamos correr para a entrada da floresta-noite-sem-fim e recitar esse poema já! Essas realidades paralelas tem de parar, estão controlando nossas escolhas, mas precisamos nos unir para acabar com isso! Ouviu bem pessoa má que está controlando a vida de crianças!</p> <button onclick ='carregarConteudo(conteudo40)'> Destino final</button>";

var conteudo39 = "<img src='imagens/briga.gif'/><p span class = 'texto'>  Você também parte para cima, mostrando que não foge de uma boa luta, vocês dois começam a brigar, cachorro quente doido grita: -É isso aí! Pega ele!! Golem treme de medo. Porém antes que a briga se estenda ainda mais, uma outra versão de vocês pula no meio da briga para separa-los (outra versão? Caramba, parece até que essa história foi controlada de diversas formas!) <br> - Parem, parem agora! Vocês não são selvagens! Talvez essa pessoa pelada com uma mordida de cobra no seu braço até seja, mas vejam, somos idênticos e aparentemente, buscamos a mesma coisa, ir para casa! Precisamos fazer isso antes que as coisas fujam mais ainda de controle, peguem essas páginas, vamos correr para a entrada da floresta e recitar esse poema já! Essas realidades paralelas tem de parar, estão controlando nossas escolhas, mas precisamos nos unir para acabar com isso! Ouviu bem pessoa má que está controlando a vida de crianças!</p> <button onclick ='carregarConteudo(conteudo40)'> Destino final</button>";

var conteudo40 = "<img src='imagens/fim.gif'/><p span class = 'texto'> Vocês três se entreolham e percebem que estão ali pelo mesmo propósito, que cada um viveu uma aventura diferente, mas que no final, todos almejam a mesma coisa, apenas voltar para casa, que o tempo que passaram nessas cidades mágicas foi muito bom, mas parece que quanto mais tempo passam naquele local, mais as coisas fogem de controle. <br> O desconhecido pelado envenenado pela cobra escreve em seu diário: - Vocês têm razão, eu fui perdendo a sanidade cada vez mais que o tempo passava, quando finalmente consegui pegar a folha do poema, não consegui recita-lo por que fiquei sem voz graças aquela cobra pessimista, fiquei enfurecido e saí sem rumo, mas não fazia ideia que vocês também estavam sendo afetados por alguma força maior que decide as nossas escolhas aqui nesse mundo, sinto muito... <br> Tudo bem – diz o clone da realidade paralela número 2 – agora que estamos todos aqui reunidos, podemos voltar para nossa vida normal, quem diria que uma mera tentativa de fugir de casa daria em tudo isso? Foi muito bom conhecer vocês, obrigada por me ajudarem nessa jornada, vocês foram os melhores seres que já conheci – diz o clone da realidade paralela número 1: <br> - Golem e cachorro quente doido, jamais que esquecerei de vocês, mandem lembranças ao gatinho do rio, obrigada por tudo... Golem e cachorro quente doido se abraçam e choram emocionados, eu nunca vi o cachorro quente deixar de ser doido por um minuto, agora ele é só um cachorro quente triste. <br> - Eu voltarei para minha biblioteca, vocês sabem o caminho até lá, caso queiram voltar, estarei de portas abertas até por que quebraram a minha. (ele volta a ficar furioso, agora sim).<br> Golem, muito triste, escreve um bilhete de despedida para seu amigo, seu primeiro e único amigo. 'sentirei saudades'.  <br> Vocês três voltam ao início da floresta-noite-sem-fim, e, recitando o poema, conseguem voltar cada um para sua respectiva realidade, sem mais escolhas, sem mais quebras da quarta parede e sem finais tristes, apenas casa.</p> <p><b>Essa história termina aqui.</p><b> <p><b>Agradecimentos especiais:</p> <br> Cachorro quente de: Omori<br> Golem de: Hilda<br> Personagem principal de: vozes na minha cabeça<br> <button onclick = 'carregarConteudo(conteudoA)'>Recomeçar a história</button>";

var elemento = document.getElementById("conteudo");

function carregarConteudo(conteudo){
    elemento.innerHTML = conteudo;
}

function mudarEstilos()  {
    //Dentro dessa função, escreva o codigo para alterar o estilo do elemento com o id "text". 
    //A cor do texto deve ser verde, o tamanho do texto deve ser 15px e a fonte escolhida deve ser Arial;
    //Escreva sua resposta no espaço abaixo.  
    //Um exemplo de alteração de estilos por javascript: text.style.fontFamily = "Comic Sans MS";
    // font-family: banana;
    
    text.style.fontFamily = "Comic Sans MS";
    text.style.color = "white";
    text.style.padding = "20";
    text.style.backgroundColor = "#00000";

}

function darkmode() {
    var element = document.body
    element.classList.toggle("dark-mode");
  }

carregarConteudo(conteudoA)
